# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
